/* ~This file is part of the Aliro library~

Copyright (C) 2023 Epistasis Lab, 
Center for Artificial Intelligence Research and Education (CAIRE),
Department of Computational Biomedicine (CBM),
Cedars-Sinai Medical Center.

Aliro is maintained by:
    - Hyunjun Choi (hyunjun.choi@cshs.org)
    - Miguel Hernandez (miguel.e.hernandez@cshs.org)
    - Nick Matsumoto (nicholas.matsumoto@cshs.org)
    - Jay Moran (jay.moran@cshs.org)
    - and many other generous open source contributors

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

(Autogenerated header, do not modify)

*/
import React, { Component } from 'react';
import { connect } from 'react-redux';
import * as actions from 'data/builder/actions';
import SceneHeader from '../SceneHeader';
import NotFound from '../NotFound';
import FetchError from '../FetchError';
import AlgorithmOptions from './components/AlgorithmOptions';
import ParameterOptions from './components/ParameterOptions';
import { Grid, Button, Icon, Popup, Loader } from 'semantic-ui-react';
import { formatDataset } from 'utils/formatter';
import { hashHistory } from 'react-router';


class Builder extends Component {
 
  constructor(props) {
    // console.log("props: ", props);
    // console.log("this.state", this.state)
    super(props);
    this.state = { dataset: null };
    this.handleSubmitExperiment = this.handleSubmitExperiment.bind(this);
    this.handleResetExperiment = this.handleResetExperiment.bind(this);
  }

  componentDidMount() {
    const { defaultAlgorithms, availableAlgorithms, setCurrentAlgorithm } = this.props;
    setCurrentAlgorithm(availableAlgorithms[0]);

    // console.log("this.props", this.props)
    // console.log("availableAlgorithms[0]",availableAlgorithms[0])
    
    if(!this.props.dataset) {
      fetch(`/api/datasets/${this.props.location.query.dataset}`)
        .then(response => {
          if(response.status >= 400) {
            throw new Error(`${response.status}: ${response.statusText}`);
          }  
          return response.json();
        })
        .then(dataset => this.setState({ dataset: dataset[0] }));
    } 
  }

  componentDidUpdate(prevProps) {
    // if finished submitting and no error, redirect
    if(prevProps.isSubmitting && !this.props.isSubmitting && !this.props.error) {
      hashHistory.push('/experiments'); // redirect to experiments page
    }
  }

  componentWillUnmount() {
    const { defaultAlgorithms, availableAlgorithms, setCurrentAlgorithm, clearError } = this.props;
    setCurrentAlgorithm(availableAlgorithms[0]);
    clearError();
  }

  handleSubmitExperiment() {
    const dataset = this.props.dataset || this.state.dataset;
    const { currentAlgorithm, currentParams, submitExperiment } = this.props;
    const validParams = Object.assign({}, currentParams, {
      dataset: dataset._id
    });

    submitExperiment(currentAlgorithm._id, validParams);
  }

  handleResetExperiment() {
    const { currentAlgorithm, setCurrentAlgorithm } = this.props;
    setCurrentAlgorithm(currentAlgorithm);
  }

  render() {
    const dataset = this.props.dataset || this.state.dataset;
    const { 
      defaultAlgorithms,
      availableAlgorithms,
      currentAlgorithm, 
      currentParams,
      isSubmitting,
      error,
      setCurrentAlgorithm,
      setParamValue
    } = this.props;



    function openTrueOrFalse_submit_experiment_popup()
  {
    if (localStorage.getItem("submit-experiment-popup") == "true"){
      return false;
    }
    else{
      return true;
    }
  }


    return (
      <div className="builder-scene">
        <SceneHeader 
          header={
            'Build New Experiment' + `${dataset ? `: ${formatDataset(dataset.name)}` : '' + '${}' }`
          } 
        />
        <Grid stretched>
          <AlgorithmOptions
            algorithms={availableAlgorithms}
            currentAlgorithm={currentAlgorithm}
            setCurrentAlgorithm={setCurrentAlgorithm}
          />
          <ParameterOptions
            params={currentAlgorithm.schema}
            currentParams={currentParams}
            setParamValue={setParamValue}
          />
        </Grid>


        <Popup 
          id = "submit-experiment-popup"
          trigger={
        <div className="builder-btns">
          <Popup
            header="Error submitting experiment:"
            content={error}
            open={error ? true : false}
            trigger={
              <Button 
                color="blue"
                size="large"
                content="Launch Experiment"
                icon={isSubmitting ? <Icon loading name="spinner" /> : null}
                disabled={isSubmitting}
                
                onClick={() => {
                  localStorage.setItem("algorithm-popup", "true");
                  // param-popup
                  localStorage.setItem("param-popup", "true");

                  localStorage.setItem("submit-experiment-popup", "true");

                  this.handleSubmitExperiment();


                }}
                  
              />
            }
          />
          <Button 
            color="grey"
            size="large"
            content="Reset"
            disabled={isSubmitting}
            onClick={this.handleResetExperiment}
          />
        </div>
          }
          
          content="Launch experiment"
          position="top left"
          
          open = {openTrueOrFalse_submit_experiment_popup()}

          onClick = { () => 
            {
              if (document.getElementById("submit-experiment-popup") != null) {
              
                document.getElementById("submit-experiment-popup").style.cssText += ';display:none !important;';

                localStorage.setItem("submit-experiment-popup", "true");
                // show the local storage on the console
                console.log("submit-experiment-popup", localStorage.getItem("submit-experiment-popup"));

              }
            }
          }
          />


      </div>
    );
  }
}

const mapStateToProps = (state, props) => (
{
  

  dataset: state.datasets.byId[props.location.query.dataset],
  defaultAlgorithms: state.preferences.data.algorithms,
  availableAlgorithms: state.preferences.data.algorithms.filter(function(algo) {

    console.log('state in mapstatetoprops', state)
    console.log('props.location.query.dataset', props.location.query.dataset)

      return algo.category==state.datasets.byId[props.location.query.dataset].files[0].prediction_type
   }),
  currentAlgorithm: state.builder.currentAlgorithm,
  currentParams: state.builder.currentParams,
  isSubmitting: state.builder.isSubmitting,
  error: state.builder.error
}

);

export { Builder };
export default connect(mapStateToProps, actions)(Builder);
