POST http://localhost:5080/chatapi/v1/chats
Content-Type: application/json

{
    "title" : "Another Chat with experiment id",
    "_experiment_id": "63f6e4987c5f93004a3e3ca8",
    "_dataset_id": "63f6e4947c5f93004a3e3ca7"
}

###

GET http://localhost:5080/chatapi/v1/chats

###

GET http://localhost:5080/chatapi/v1/chats/63ffb16342f8d8282acbcc8d

###

PATCH http://localhost:5080/chatapi/v1/chats/63ffb16342f8d8282acbcc6d
Content-Type: application/json

{
    "title" : "Chat with no experiment id",
    "_experiment_id": "63f6e4987c5f93004a3e3ca8",
    "_dataset_id": "63f6e4947c5f93004a3e3ca7"
}

###

DELETE http://localhost:5080/chatapi/v1/chats/63ffb16342f8d8282acbcc8d

###
POST http://localhost:5080/chatapi/v1/chatlogs
Content-Type: application/json

{
    "_chat_id" : "63ffb16342f8d8282acbcc8d",
    "message" : "Hello there from cyberspace!",
    "message_type" : "text",
    "who" : "openai"
}

###

PATCH http://localhost:5080/chatapi/v1/chatlogs/63ffc80142f8d8282acbccb6
Content-Type: application/json

{
    "message" : "Hello from cyberspace!",
    "message_type" : "text",
    "who" : "openai"
}