POST http://localhost:5080/chatapi/v1/chat
Content-Type: application/json

{
    "title" : "Hello",
    "_experient_id": "63f6e4987c5f93004a3e3ca8",
    "_dataset_id": "63f6e4947c5f93004a3e3ca7"
}

###

POST http://localhost:5080/chatapi/v1/chatlog/
Content-Type: application/json

{
    "_chat_id" : "63f6e54fc76ccd8396386d03",
    "message" : "Hello there from cyberspace!",
    "message_type" : "text",
    "who" : "openai"
}

###

GET http://localhost:5080/chatapi/v1/chat

###

GET http://localhost:5080/chatapi/v1/chat/63f6e54fc76ccd8396386d03

###
