version: '3'

services:
  doc_builder:
    build:
      context: .
      dockerfile: docs/Dockerfile
      args:
        - USE_WHEELS=0
    working_dir: /appsrc/docs
    command: bash -c "make html"
    tty: true
    stdin_open: true
    volumes:
      - "./:/appsrc"
      - "/appsrc/lab/webapp/node_modules"

  doc_api_builder:
    image: "node:18.13.0-slim"
    command: bash -c "npm i -g raml2html && 
      raml2html /appsrc/lab/api.raml > /appsrc/target/ai_docs/html/lab_api_source.html && 
      raml2html /appsrc/docs/APIs/openai.raml > /appsrc/target/ai_docs/html/openai_source.html &&
      raml2html /appsrc/docs/APIs/chatapi.raml > /appsrc/target/ai_docs/html/chatapi_source.html"
    volumes:
      - "./:/appsrc"
