version: '3'

services:
  unit_tester:
    build:
      context: .
      dockerfile: tests/unit/Dockerfile
    working_dir: /appsrc
    command: bash -c "cd docs && make html"
    tty: true
    stdin_open: true
    volumes:
      - "./:/appsrc"
      - "/appsrc/lab/webapp/node_modules"
