version: '3'

services:
  doc_builder:
    build:
      context: .
      dockerfile: docs/Dockerfile
      args:
        - USE_WHEELS=${USE_WHEELS}
    working_dir: /appsrc/docs
    command: bash -c "make html"
    tty: true
    stdin_open: true
    volumes:
      - "./:/appsrc"
      - "/appsrc/lab/webapp/node_modules"
