version: '3'

services: 
  lab:
    build: dockers/lab
    tty: true
    volumes: 
      - "./:/appsrc"
    ports:
      - "443:443"
      - "5080:5080"
    env_file: common.env

  machine:
    build: dockers/machine
    tty: true
    volumes: 
      - "./:/appsrc"
    ports: 
      - "5081:5081"
    env_file: common.env

  dbmongo:
    build: dockers/dbmongo
    tty: true
    volumes: 
      - "./:/appsrc"
    ports:  
      - "27017:27017"
    env_file: common.env