###

POST http://localhost:5080/execapi/v1/executions
Content-Type: application/json

{
  "src_code": "import sklearn.decomposition\nimport matplotlib.pyplot as plt\n\npca = sklearn.decomposition.PCA(n_components=2)\ndf = pca.fit_transform(df.drop('target', axis=1))\n\nplt.scatter(df[:, 0], df[:, 1])\nplt.xlabel('PC 1')\nplt.ylabel('PC 2')\nplt.title('PCA Plot of Iris Dataset')\nplt.savefig('iris_pca.png')\n",
  "dataset_id": "6434a0fe9c33cd004aa10011",
  "experiment_id": "6434a1039c33cd004aa10012"
}

###

GET http://localhost:5080/execapi/v1/executions/64346c2ee97e044e16d642d7

###

POST http://localhost:5080/execapi/v1/executions/643454b92138bd29cd7b1670/files
Content-Type: application/json

{
  "file_path": "/appsrc/machine/code_runs"
}

###

GET http://localhost:5080/api/v1/files/6435f0485a15a86c5f84b826