GET http://localhost:5080/openai/v1/configs

###

GET http://localhost:5080/openai/v1/configs/63ffa8f9fe67714b24cf5106

###

POST http://localhost:5080/openai/v1/configs
Content-Type: application/json

{
    "api_key" : "1a2b3c4d5e6f7g8h9i0j",
    "org_id" : "Personal"
}

###

PATCH http://localhost:5080/openai/v1/configs/63ffa8f9fe67714b24cf5106
Content-Type: application/json

{
    "org_id" : "user_org_id_test",
    "api_key" : "user_api_key_test"
}

###

DELETE http://localhost:5080/openai/v1/configs/63ffa8f9fe67714b24cf5106

###

GET http://localhost:5080/openai/v1/models

###

POST http://localhost:5080/openai/v1/completions
Content-Type: application/json

{
    "model" : "code-davinci-001",
    "prompt" : "Test",
    "max_tokens" : 7,
    "temperature" : 0,
    "top_p" : 1,
    "n" : 1,
    "stream" : false,
    "logprobs" : null,
    "stop" : "\n"
}

###