###

POST http://localhost:5080/runapi/v1/runs
Content-Type: application/json

{
  "src_code": "import numpy as np\ncol = df[\"sepal-length\"]\nz_scores = np.abs((col - col.mean()) / col.std())\nthreshold = 3\ncleaned_df = df[z_scores <= threshold]\ncleaned_df.to_csv(\"/appsrc/machine/code_runs/1234/cleaned_data.csv\", index=False)\n",
  # "src_code": "print(df.head(10))",
  "dataset_id": "642e165995cc6c004a85d429",
  "experiment_id": "1234"
}