#%RAML 1.0
---
title: Chat API
version: v1
baseUri: http://localhost:5080/chatapi/{version}
mediaType: application/json
types:
  Chat: !include DataTypes/chat.raml
  Chatlog: !include DataTypes/chatlog.raml

/chats:
  get:
    description: Retrieve all chats
    responses:
      200:
        body:
          application/json:
            type: Chat[]
            example: !include Examples/Chats/GetAll.raml
      500:
        body:
          application/json:
            type: object
            example: { message: 'Failed to connect to database' }
  post:
    description: Create a chat
    body:
      application/json:
        type: Chat
        example: !include Examples/Chats/Create.raml
    responses:
      201:
        body:
          application/json:
            type: Chat
            example: !include Examples/Chats/GetOne.raml
      400:
        body:
          application/json:
            type: object
            example: { message: 'Must provide a _dataset_id' }
  /{id}:
    get:
      description: Retrieve a specific chat and all it's associated chatlogs
      responses:
        200:
          body:
            application/json:
              type: object
              example: !include Examples/Chats/GetOneChat.raml
        404:
          body:
            application/json:
              type: object
              example: { message: 'Cannot find chat: 63f7bc2da70e99abe4e83b9c' }
        500:
          body:
            application/json:
              type: object
              example: { message: 'Failed to connect to database' }
    patch:
      description: Update a specific chat
      body:
        application/json:
          type: Chat
          example: !include Examples/Chats/Create.raml
      responses:
        200:
          body:
            application/json:
              type: Chat
              example: !include Examples/Chats/GetOne.raml
        400:
          body:
            application/json:
              type: object
              example: { message: 'Error message' }
        404:
          body:
            application/json:
              type: object
              example: { message: 'Cannot find chat: 63f7bc2da70e99abe4e83b9c' }
    delete:
      description: Delete a specific chat and all it's associated chatlogs
      responses:
        200:
          body:
            application/json:
              type: object
              example: { message: 'Deleted chat 63f7bc2da70e99abe4e83b9c'}
        404:
          body:
            application/json:
              type: object
              example: { message: 'Cannot find chat: 63f7bc2da70e99abe4e83b9c' }
        500:
          body:
            application/json:
              type: object
              example: { message: 'Failed to connect to database' }
/chatlogs:
  post:
    description: Create a chat log entry
    body:
      application/json:
        type: Chatlog
        example: !include Examples/Chatlogs/CreateText.raml
    responses:
      201:
        body:
          application/json:
            type: Chatlog
            example: !include Examples/Chatlogs/GetOneText.raml
      400:
        body:
          application/json:
            type: object
            example: { message: 'Must provide a _chat_id' }
  /{id}:
    patch:
      description: Update a specific chatlog entry
      body:
        application/json:
          type: Chatlog
          example: !include Examples/Chatlogs/CreateText.raml
      responses:
        200:
          body:
            application/json:
              type: Chatlog
              example: !include Examples/Chatlogs/GetOneText.raml
        400:
          body:
            application/json:
              type: object
              example: { message: 'Cannot update _chat_id' }
        404:
          body:
            application/json:
              type: object
              example: { message: 'Cannot find chatlog: 6144c03406a0c0a9d9f9d91c' }