#!/bin/bash
#DPL 
basedir=`pwd`
network='pennai';
running_hosts=`docker ps --filter network=$network --format "table {{.Names}}" | tail -n +2 | sort`
hosts=`ls | grep -v toggle| sort`
num_running=`echo "$running_hosts" | wc -w`
num_hosts=`echo "$hosts" | wc -w`
if [ "$hosts" == "$running_hosts" ] ; then
    echo "up and running";
    docker_state=2;
else
    echo "$num_running of $num_hosts are running" ;
    docker_state=1;
fi;

if [ "$num_running" == 0 ]; then
    docker_state=0;
fi;


docker_init()
{
 docker_destroy;
  netstate=`docker network create $network`;
  for host in $hosts; do
    cd $basedir/$host && make  && make create && docker start $host 
  done
}
# starts the dockers
docker_destroy()
{
  for host in $hosts; do
    cd $basedir/$host && ./killall.sh 
  done
  netstate=`docker network rm $network`;
}

if [ "$docker_state" == 0 ] ; then
  echo "docker_init";
  docker_init;
else
  echo "docker_destroy";
  docker_destroy;
fi;
