#!/bin/bash
#DPL 
basedir=`pwd`
# load variables from vars file
. $basedir/vars
if [ "$1" != "" ] ; then
   echo "running shared env:"
   echo "container:/share/devel->host:$1"
   export SHARE_PATH=$1;
   export IFROOT=/share/devel;
   cmd='createshared';
else
   cmd='create'
fi;

#check to see if there's a running host for each directory
running_hosts=`docker ps --filter network=${NETWORK} --format "table {{.Names}}" | tail -n +2 | sort`
hosts=$(ls -d */ | tr -d \/)
num_running=`echo "$running_hosts" | wc -w`
num_hosts=`echo "$hosts" | wc -w`
if [ "$hosts" == "$running_hosts" ] ; then
    echo "up and running";
    docker_state=2;
else
    echo "$num_running of $num_hosts are running" ;
    docker_state=1;
fi;

if [ "$num_running" == 0 ]; then
    docker_state=0;
fi;

docker_init()
{
  docker_destroy;
  netstate=`docker network create ${NETWORK}`;
  for host in $hosts; do
    cd $basedir/$host && make  && make $cmd && docker start $host
  done
}
# starts the dockers
docker_destroy()
{
  for host in $hosts; do
    cd $basedir/$host && ./killall.sh 
  done
  netstate=`docker network rm ${NETWORK}`;
}

if [ "$docker_state" == 0 ] ; then
  echo "docker_init";
  docker_init;
else
  echo "docker_destroy";
  docker_destroy;
fi;
