language: node_js
node_js:
  - 'node'
services:
  - mongodb
env:
  global:
    - MONGODB_URL="mongo://travis:test@localhost:27017"
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
cache:
  directories:
    - node_modules
    - bower_components
deploy:
  provider: heroku
  api_key:
    secure: EuqyRMAHZATGmXBvDhVXCl2QN6zi8/NZyOf6EuPLtoTFjBgNjPO9AfqbclOy1bLBYgD1FS6B7KPqJBYo+hyg8dnz962DgtDB2geeTpRGciFfEElsWtNwyCejUeRM0i/xUW4UZohTjoYPyd0mW5jPJOlMBR/bzU0+5yNQ79SIiOAPZxaw7A/efdzT4oHw5hGnOsZA9tJ0/xbrb2NtVs0BWGQBjIkjJKRU1E6RP1NGIe2STqzwYyGFZ8YSD/rKc60cU8E/3gMMIaeiOLvF7PzjFpSVde96zWscBE2vJwJZvz69I3O3EPdQlTprenR5wdSe2GHCED7BES5MXuEa5gEUVlheFEAk7+Az8pUm93A3Ebk+uhqOfL4fLx/Rm/DSVRYcPm51DpBHh7C6noSxEq5cABNG/OXYIs/8uyWJuNME5qZjRJmFL/TRT+o0r7INUhTTr73tmoW79Spyknsogj1eEclq5VpiIfQD9acUWhALgabwqjus2JMQ71ZHg2FECgk0XP6KsgtgkfwMJekQPkb1/sti7CIhpjyO+ddZ4Oint66mw6Ty8WGDcuEniAyxwR78FkJDVAwgAs6VIECoxRN2VJFJUqxLi18tCJMA9qKw1nRLcEctff6edGJvTId43/CbN9jaKKkdU/ULLW7q9z/QVmj3eq0tfYKz8iFcRToWZkI=
  app: fglab
  on:
    repo: Kaixhin/FGLab
  skip_cleanup: true
