/* ~This file is part of the Aliro library~

Copyright (C) 2023 Epistasis Lab, Cedars-Sinai Medical Center

Aliro is maintained by:
    - Jun Choi (hyunjun.choi@cshs.org)
    - Miguel Hernandez (miguel.e.hernandez@cshs.org)
    - Nick Matsumoto (nicholas.matsumoto@cshs.org)
    - Jay Moran (jay.moran@cshs.org)
    - and many other generous open source contributors

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

(Autogenerated header, do not modify)

*/
const {app, BrowserWindow} = require('electron')
const url = require('url')
const path = require('path')
 
let win
 
function createWindow() {
   win = new BrowserWindow(
    {width: 1800, 
    height: 1200,
    icon: path.join(__dirname, 'build/rpi-imager.icns')
})
   win.loadURL(url.format ({
      
      pathname: path.join(__dirname, 'index.html'),
      protocol: 'file:',
      slashes: true
      
    //   make all path relative to the index.html file
    
   }))
//    print the __dirname
    // console.log(__dirname)
}
 


app.on('ready', createWindow)