/* ~This file is part of the Aliro library~

Copyright (C) 2023 Epistasis Lab, 
Center for Artificial Intelligence Research and Education (CAIRE),
Department of Computational Biomedicine (CBM),
Cedars-Sinai Medical Center.

Aliro is maintained by:
    - Hyunjun Choi (hyunjun.choi@cshs.org)
    - Miguel Hernandez (miguel.e.hernandez@cshs.org)
    - Nick Matsumoto (nicholas.matsumoto@cshs.org)
    - Jay Moran (jay.moran@cshs.org)
    - and many other generous open source contributors

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

(Autogenerated header, do not modify)

*/
// make varialbe json format

var iris_tree_Data = {
    "name": "petal length (cm) > 2.45000004768",
    "pred": "100 of no, 50 of yes",
    "children": [
        {
            "children": [
                {
                    "children": [
                        {
                            
                            "name": "The number of data = 43",
                            "children": [
  
  
  
                               {
                                    
                                    "name": "0 = setosa",
                                    "children": [],
                                    "side": "right",
                                    "type": "categorical",
                                    "size": 0,
                                    "pred": "0 of no, 0 of yes"
                                },
                                {
                                    
                                  "name": "0 = versicolor",
                                  "children": [],
                                  "side": "right",
                                  "type": "categorical",
                                  "size": 0,
                                  "pred": "0 of no, 0 of yes"
                              }
                              ,
                                {
                                    
                                  "name": "43 = virginica",
                                  "children": [],
                                  "side": "right",
                                  "type": "categorical",
                                  "size": 43,
                                  "pred": "43 of no, 0 of yes"
                              }
  
                            ],
                            "side": "right",
                            "type": "categorical",
                            "size": 43,
                            "pred": "0 of no, 0 of yes"
                        },
                        {
                            
                          "name": "The number of data = 3",
                          "children": [
  
  
                            {
                                    
                              "name": "0 = setosa",
                              "children": [],
                              "side": "right",
                              "type": "categorical",
                              "size": 0,
                              "pred": "0 of no, 0 of yes"
                          },
                          {
                              
                            "name": "1 = versicolor",
                            "children": [],
                            "side": "right",
                            "type": "categorical",
                            "size": 1,
                            "pred": "1 of no, 0 of yes"
                        }
                        ,
                          {
                              
                            "name": "2 = virginica",
                            "children": [],
                            "side": "right",
                            "type": "categorical",
                            "size": 2,
                            "pred": "2 of no, 0 of yes"
                        }
  
  
  
  
                          ],
                          "side": "right",
                          "type": "categorical",
                          "size": 3,
                          "pred": "0 of no, 0 of yes"
                      }
  
                    ],
                    "name": "petal length (cm) > 4.85000038147",
                    "side": "right",
                    "type": "categorical",
                    "size": 46,
                    "pred": "43 of no, 3 of yes"
                },
                {
                    
                    "name": "petal length (cm) > 4.94999980927",
                    "children": [
  
                      {
                              
                          "name": "The number of data = 6",
                          "children": [
    
    
    
                             {
                                  
                                  "name": "0 = setosa",
                                  "children": [],
                                  "side": "right",
                                  "type": "categorical",
                                  "size": 0,
                                  "pred": "0 of no, 0 of yes"
                              },
                              {
                                  
                                "name": "2 = versicolor",
                                "children": [],
                                "side": "right",
                                "type": "categorical",
                                "size": 2,
                                "pred": "2 of no, 0 of yes"
                            }
                            ,
                              {
                                  
                                "name": "4 = virginica",
                                "children": [],
                                "side": "right",
                                "type": "categorical",
                                "size": 4,
                                "pred": "4 of no, 0 of yes"
                            }
    
                          ],
                          "side": "right",
                          "type": "categorical",
                          "size": 6,
                          "pred": "0 of no, 0 of yes"
                      },
                      
                      {
                          
                        "name": "The number of data = 48",
                        "children": [
    
    
                          {
                                  
                            "name": "0 = setosa",
                            "children": [],
                            "side": "right",
                            "type": "categorical",
                            "size": 0,
                            "pred": "0 of no, 0 of yes"
                        },
                        {
                            
                          "name": "47 = versicolor",
                          "children": [],
                          "side": "right",
                          "type": "categorical",
                          "size": 47,
                          "pred": "47 of no, 0 of yes"
                      }
                      ,
                        {
                            
                          "name": "1 = virginica",
                          "children": [],
                          "side": "right",
                          "type": "categorical",
                          "size": 1,
                          "pred": "1 of no, 0 of yes"
                      }
    
    
    
    
                        ],
                        "side": "right",
                        "type": "categorical",
                        "size": 48,
                        "pred": "0 of no, 0 of yes"
                      }
    
                        
    
                      ],
                    "side": "left",
                    "type": "categorical",
                    "size": 54,
                    "pred": "6 of no, 48 of yes"
                }
            ],
            "name": "petal width (cm) > 1.75",
            "side": "right",
            "type": "numerical",
            "size": 100,
            "pred": "46 of no, 54 of yes"
        },{
          "name": "The number of data = 50",
          "children": [
  
  
  
              {
                  
                  "name": "50 = setosa",
                  "children": [],
                  "side": "right",
                  "type": "categorical",
                  "size": 50,
                  "pred": "50 of no, 0 of yes"
              },
              {
                  
                "name": "0 = versicolor",
                "children": [],
                "side": "right",
                "type": "categorical",
                "size": 0,
                "pred": "0 of no, 0 of yes"
            }
            ,
              {
                  
                "name": "0 = virginica",
                "children": [],
                "side": "right",
                "type": "categorical",
                "size": 0,
                "pred": "0 of no, 0 of yes"
            }
  
          ],
          "side": "right",
          "type": "categorical",
          "size": 50,
          "pred": "0 of no, 0 of yes"
        }
    ],
    "side": "right",
    "size": 150
  }


var iris_tree_Data = {
  "name": "petal length (cm) > 2.45000004768",
  "children": [
    {
      "name": "petal width (cm) > 1.75",
      "children": [
        {
          "name": "petal length (cm) > 4.85000038147",
          "children": [
            {
              "name": "0 of setosa, 0 of versicolor, 43 of virginica"
            },
            {
              "name": "0 of setosa, 1 of versicolor, 2 of virginica"
            }
          ]
        },
        {
          "name": "petal length (cm) > 4.94999980927",
          "children": [
            {
              "name": "0 of setosa, 2 of versicolor, 4 of virginica"
            },
            {
              "name": "0 of setosa, 47 of versicolor, 1 of virginica"
            }
          ]
        }
      ]
    },
    {
      "name": "50 of setosa, 0 of versicolor, 0 of virginica"
    }
  ]
}
  
  
  
  