version: '3'

services:
  lab:
    image: "moorelab/aliro_lab:${TAG}"
    tty: true
    stdin_open: true
    volumes:
      - "/appsrc"
      - "./data/datasets/user:/appsrc/data/datasets/user"
      - "./data/recommenders:/appsrc/data/recommenders/pennaiweb"
      - "./target:/appsrc/target"
    ports:
      - "5080:5080"
    env_file:
      - ./config/common.env
      - ./config/ai.env
    depends_on:
      - dbmongo

  machine:
    image: "moorelab/aliro_machine:${TAG}"
    tty: true
    stdin_open: true
    volumes:
      - "/appsrc"
      - "./target:/appsrc/target"
    ports:
      - "5081:5081"
    env_file: ./config/common.env
    environment:
      - MACHINE_PORT=5081
    depends_on:
      - lab
      - dbmongo

##########################################################
# Uncomment for additoinal 'machine' container instances #
##########################################################
#  machine_2:
#    image: "moorelab/aliro_machine:${TAG}"
#    tty: true
#    stdin_open: true
#    volumes:
#      - "/appsrc"
#      - "./target:/appsrc/target"
#    ports:
#      - "5082:5082"
#    env_file: ./config/common.env
#    environment:
#      - MACHINE_PORT=5081
#    depends_on:
#      - lab
#      - dbmongo
#
#  machine_3:
#    image: "moorelab/aliro_machine:${TAG}"
#    tty: true
#    stdin_open: true
#    volumes:
#      - "/appsrc"
#      - "./target:/appsrc/target"
#    ports:
#      - "5083:5083"
#    env_file: ./config/common.env
#    environment:
#      - MACHINE_PORT=5081
#    depends_on:
#      - lab
#      - dbmongo
#
#  machine_4:
#    image: "moorelab/aliro_machine:${TAG}"
#    tty: true
#    stdin_open: true
#    volumes:
#      - "/appsrc"
#      - "./target:/appsrc/target"
#    ports:
#      - "5084:5084"
#    env_file: ./config/common.env
#    environment:
#      - MACHINE_PORT=5081
#    depends_on:
#      - lab
#      - dbmongo
#
#  machine_5:
#    image: "moorelab/aliro_machine:${TAG}"
#    tty: true
#    stdin_open: true
#    volumes:
#      - "/appsrc"
#      - "./target:/appsrc/target"
#    ports:
#      - "5085:5085"
#    env_file: ./config/common.env
#    environment:
#      - MACHINE_PORT=5081
#    depends_on:
#      - lab
#      - dbmongo
#
#  machine_6:
#    image: "moorelab/aliro_machine:${TAG}"
#    tty: true
#    stdin_open: true
#    volumes:
#      - "/appsrc"
#      - "./target:/appsrc/target"
#    ports:
#      - "5086:5086"
#    env_file: ./config/common.env
#    environment:
#      - MACHINE_PORT=5081
#    depends_on:
#      - lab
#      - dbmongo

  dbmongo:
    image: "moorelab/aliro_dbmongo:${TAG}"
    tty: true
    stdin_open: true
    ports:
      - "27017:27017"
    env_file: ./config/common.env
