version: '3'

services:
  lab:
    image: "moorelab/pennai_lab:${TAG}"
    tty: true
    stdin_open: true
    volumes:
      - "/appsrc"
      - "./data/datasets/user:/appsrc/data/datasets/user"
      - "./target:/appsrc/target"
    ports:
      - "5080:5080"
    env_file:
      - ./config/common.env
      - ./config/ai.env
    depends_on:
      - dbmongo

  machine:
    image: "moorelab/pennai_machine:${TAG}"
    tty: true
    stdin_open: true
    volumes:
      - "/appsrc"
      - "./target:/appsrc/target"
    ports:
      - "5081:5081"
    env_file: ./config/common.env
    environment:
      - MACHINE_PORT=5081
    depends_on:
      - lab
      - dbmongo

  dbmongo:
    image: "moorelab/pennai_dbmongo:${TAG}"
    tty: true
    stdin_open: true
    ports:
      - "27017:27017"
    env_file: ./config/common.env
