#%RAML 1.0
---
title: FGLab API
baseUri: http://fglab.com/api/{version}
version: v1
mediaType: application/json
/projects:
  get:
    description: Retrieve all projects
    responses:
      200:
        body:
          example: |
            [
              {
                "_id": "562237f33774694c5a4814bb",
                "name":"calinski-harabasz",
                "schema": {
                  "algorithm": {
                    "type": "enum",
                    "default": "kmeans",
                    "values": ["kmeans", "linkage", "gmdistribution"]
                  },
                  "k": {
                    "type": "int",
                    "default": 3
                  }
                }
              },
              {
                "_id": "56297e87d1a19b9c0e21c70a",
                "name":"bayesian-optimisation",
                "schema": {
                  "x": {
                    "type": "float",
                    "default": 2
                  },
                  "y": {
                    "type": "float",
                    "default": 7
                  }
                }
              }
            ]
  /{projectId}:
    get:
      description: Retrieve a specific project by ID
      responses:
        200:
          body:
            example: |
              {
                "_id": "56297e87d1a19b9c0e21c70a",
                "name":"bayesian-optimisation",
                "schema": {
                  "x": {
                    "type": "float",
                    "default": 2
                  },
                  "y": {
                    "type": "float",
                    "default": 7
                  }
                }
              }
    /experiment:
      post:
        description: Submit a single experiment
        responses:
          201:
            body:
              example: |
                {
                  "_id": "562a12bd612a17b20f99a143"
                }
          400:
            body:
              example: |
                {
                  "error": "Project ID 562237f33774694c5a4814bb does not exist"
                }
          500:
            body:
              example: |
                {
                  "error": "Experiment failed to run"
                }
          501:
            body:
              example: |
                {
                  "error": "No machine capacity available"
                }
    /batch:
      post:
        description: Submit a batch of experiments
        queryParameters:
          retry:
            displayName: Retry Timeout
            description: Time (s) between retries after single failed experiment submission
            type: integer
            minimum: 1
            default: 3600
            example: 60
        responses:
          201:
            body:
              example: |
                {
                  "status": "Started"
                }
          400:
            body:
              example: |
                {
                  "error": "Project ID 562237f33774694c5a4814bb does not exist"
                }
/experiments:
  get:
    description: Retrieve all experiments
    responses:
      200:
        body:
          example: |
            [
              {
                "_id": "562aa755023155351a2ff061",
                "_options": {
                  "y": 8.59954833984375,
                  "x": 0.07110595703125
                },
                "_project_id": "56297e87d1a19b9c0e21c70a",
                "_machine_id": "5628fb1b17de50be077be348",
                "_files": [],
                "_status": "success",
                "_started": "2015-10-23T21:32:05.995Z",
                "_finished": "2015-10-23T21:32:31.107Z",
                "_scores": {
                  "value": 97.4392476647487
                }
              },
              {
                "_id": "562aa731023155351a2ff060",
                "_options": {
                  "y": 15,
                  "x": -5
                },
                "_project_id": "56297e87d1a19b9c0e21c70a",
                "_machine_id": "5628fb1b17de50be077be348",
                "_files": [],
                "_status": "success",
                "_started": "2015-10-23T21:31:29.322Z",
                "_finished": "2015-10-23T21:31:58.435Z",
                "_scores": {
                  "value" :12.87494045337280
                }
              }
            ]
  /{experimentId}:
    get:
      description: Retrieve a specific experiment by ID
      responses:
        200:
          body:
            example: |
              {
                "_id": "562aa731023155351a2ff060",
                "_options": {
                  "y": 15,
                  "x": -5
                },
                "_project_id": "56297e87d1a19b9c0e21c70a",
                "_machine_id": "5628fb1b17de50be077be348",
                "_files": [],
                "_status": "success",
                "_started": "2015-10-23T21:31:29.322Z",
                "_finished": "2015-10-23T21:31:58.435Z",
                "_scores": {
                  "value" :12.87494045337280
                }
              }
/machines:
  get:
    description: Retrieve all machines
    responses:
      200:
        body:
          example: |
            [
              {
                "_id": "5628fb1b17de50be077be348",
                "address": "http://cl21.uni.ac.uk:5081",
                "hostname": "cl21",
                "os": {
                  "type": "Darwin",
                  "platform": "darwin",
                  "arch": "x64",
                  "release": "13.4.0"
                },
                "cpus": ["Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz", "Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz", "Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz", "Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz", "Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz", "Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz", "Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz", "Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz"],
                "mem": "8GB",
                "gpus": [],
                "projects": {
                  "562cfff058bcb96a113cb946": {
                    "cwd": "./test",
                    "command": "node",
                    "args": ["rand.js","-optParams"],
                    "options": "plain",
                    "capacity": "0.3",
                    "results": "./test/experiments"
                  }
                }
              },
              {
                "_id": "563356d5616ea83042a60711",
                "address": "http://gpu2.uni.ac.uk:5081",
                "cpus": ["Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz", "Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz", "Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz", "Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz", "Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz", "Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz", "Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz", "Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz"],
                "gpus": ["NVIDIA Corporation GK110B [GeForce GTX Titan Black] (rev a1)"],
                "hostname": "gpu2",
                "mem": "23.53GB",
                "os": {
                  "type": "Linux",
                  "platform": "linux",
                  "arch": "x64",
                  "release": "3.19.0-31-generic"
                },
                "projects": {
                  "562143a0f78b4abe2220ac1d": {
                    "cwd": "/home/user/FGMachine/test",
                    "command": "node",
                    "args": ["rand.js","-optParameter"],
                    "options": "plain",
                    "capacity": 0.9,
                    "results": "/home/user/FGMachine/test/experiments"
                  }
                }
              }
            ]
  /{machineId}:
    get:
      description: Retrieve a specific machine by ID
      responses:
        200:
          body:
            example: |
              {
                "_id": "563356d5616ea83042a60711",
                "address": "http://gpu2.uni.ac.uk:5081",
                "cpus": ["Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz", "Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz", "Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz", "Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz", "Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz", "Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz", "Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz", "Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz"],
                "gpus": ["NVIDIA Corporation GK110B [GeForce GTX Titan Black] (rev a1)"],
                "hostname": "gpu2",
                "mem": "23.53GB",
                "os": {
                  "type": "Linux",
                  "platform": "linux",
                  "arch": "x64",
                  "release": "3.19.0-31-generic"
                },
                "projects": {
                  "562143a0f78b4abe2220ac1d": {
                    "cwd": "/home/user/FGMachine/test",
                    "command": "node",
                    "args": ["rand.js","-optParameter"],
                    "options": "plain",
                    "capacity": 0.9,
                    "results": "/home/user/FGMachine/test/experiments"
                  }
                }
              }
    /projects:
      post:

        description: Registers machine projects
        body:
          application/json:
            example:
              {
              [ { name: 'BernoulliNB',
                      command: 'python',
                      cwd: 'machine/learn/BernoulliNB',
                      args: [Object],
                      options: 'double-dash',
                      capacity: '1',
                      results: 'machine/learn/BernoulliNB/tmp' },
                    { name: 'DecisionTreeClassifier',
                      command: 'python',
                      cwd: 'machine/learn/DecisionTreeClassifier',
                      args: [Object],
                      options: 'double-dash',
                      capacity: '1',
                      results: 'machine/learn/DecisionTreeClassifier/tmp' },
                    { name: 'DecisionTreeRegressor',
                      command: 'python',
                      cwd: 'machine/learn/DecisionTreeRegressor',
                      args: [Object],
                      options: 'double-dash',
                      capacity: '1',
                      results: 'machine/learn/DecisionTreeRegressor/tmp' }
              ]
              }
/files:
  /{fileId}:
    get:
      description: Retrieve a specific file by ID
      responses:
        200:
          body:
            binary/octet-stream:
/webhooks:
  post:
    description: Create a new webhook
    responses:
      201:
        body:
          example: |
            {
              "status": "Registered",
              "options": {
                "url": "http://gpu2.uni.ac.uk:5000/webhook",
                "objects": "experiments",
                "object_id": "562aa731023155351a2ff060",
                "event": "finished"
              }
            }
      400:
        body:
          example: |
            {
              "error": "Invalid or empty URL"
            }
