#!/bin/bash
### BEGIN INIT INFO
# Provides:          /share/devel/sps/bobber/
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: forever running /share/devel/sps/bobber/
# Description:       /share/devel/sps/bobber/
### END INIT INFO
#
# initd a node app
# Based on a script posted by https://gist.github.com/jinze at https://gist.github.com/3748766
#

# Source function library.
#. /lib/lsb/init-functions

pidFile="/share/devel/Gp/lab/log/server.pid"
logFile="/share/devel/Gp/lab/log/server.log"

command="node"
scriptName="lab.js"
baseDir="/share/devel/Gp/lab"
nodeApp=$baseDir/$scriptName
foreverApp="forever"

start() {
	echo "Starting $nodeApp"

	# Notice that we change the PATH because on reboot
   # the PATH does not include the path to node.
   # Launching forever with a full path
   # does not work unless we set the PATH.
   PATH=/usr/local/bin:$PATH
#	export NODE_ENV=production
   #PORT=80
   $foreverApp start --pidFile $pidFile -l $logFile -w --watchDirectory $baseDir --watchIgnore  $baseDir/views/ --watchIgnore  $baseDir/node_modules/  --watchIgnore  "$baseDir/log/**" --watchIgnore "$baseDir/public/**" --watchIgnore "**/.git/**" --watchIgnore "$baseDir/tmp/**" -a -d -c "$command" $nodeApp
#   $foreverApp start --pidFile $pidFile -l $logFile -w --watchIgnore '.git/**' --watchIgnore  '!{server.js,{config,controllers,experiments,models,schema}/**}'  -a -d -c "$command" $nodeApp
   RETVAL=$?
}

restart() {
	echo -n "Restarting $nodeApp"
	$foreverApp restart $nodeApp
	RETVAL=$?
}

stop() {
	echo -n "Shutting down $nodeApp"
   $foreverApp stop $nodeApp
   RETVAL=$?
}

status() {
   echo -n "Status $nodeApp"
   $foreverApp --pidFile $pidFile list
   RETVAL=$?
}

case "$1" in
   start)
        start
        ;;
    stop)
        stop
        ;;
   status)
        status
       ;;
   restart)
   	restart
        ;;
	*)
       echo "Usage:  {start|stop|status|restart}"
       exit 1
        ;;
esac
exit $RETVAL
